// src/components/leftnavbar/avatar/avatar.component.ts
import * as React from 'react';

export const Avatar = () => (
    <></>
);

/*
@Component({
    selector: 'avatar',
    providers: [AvatarService],
    templateUrl: './avatar.template.html',
    styleUrls: ['./avatar.style.sass']
})
export class AvatarComponent implements OnInit {
    private _avatar = {};
    constructor(private readonly _avatarService: AvatarService) { }

    ngOnInit() {
        // this._avatarService.getAvatarInfo()
        //     .subscribe(r => this._avatar = r);
    }
}
*/

// src/app/leftnavbar/avatar/avatar.component.ts
import { Component, OnInit } from '@angular/core';
import { AvatarService } from './avatar.service';

@Component({
    selector: 'avatar',
    providers: [AvatarService],
    templateUrl: './avatar.template.html',
    styleUrls: ['./avatar.style.sass']
})
export class AvatarComponent implements OnInit {
    private _avatar = {};
    constructor(private readonly _avatarService: AvatarService) { }

    ngOnInit() {
        // this._avatarService.getAvatarInfo()
        //     .subscribe(r => this._avatar = r);
    }
}
