// src/components/shared/Spinner.tsx
import * as React from 'react';
import * as NProgress from 'nprogress';
import './Spinner.css';

type SpinnerProps = {
    shouldSpin: boolean
}

const updateSpinner = (shouldSpin: boolean) => {
    NProgress.configure({
        showSpinner: true,
        minimum: 0.1,
        speed: 500,
        trickleSpeed: 100
    });
    shouldSpin ? NProgress.start() : NProgress.done();
};

// TODO: replace fdsf with childrens
export const Spinner = ({ shouldSpin }: SpinnerProps) => {
    updateSpinner(shouldSpin);
    return <span> fdsf </span>;
};

// src/app/shared/spinner/spinner.component.ts
import { Component, Input } from '@angular/core';
import * as NProgress from 'nprogress';

@Component({
    selector: 'spinner',
    templateUrl: './spinner.template.html'
})
export class SpinnerComponent {
    @Input()
    set isSpinning(value: boolean) {
        NProgress.configure({
            showSpinner: false,
            minimum: 0.1,
            speed: 500,
            trickleSpeed: 100
        });
        value ? NProgress.start() : NProgress.done();
    }
}
